from .DataStorage import DataStorageGUI
from .MultiMotor import MultiMotorGUI
from .Memory import ControllerMemory
from .MultiDetector import MultiDetectorGUI
from .MultiDetectorOpt import MultiDetectorGUI_Opt
from .PreCorrection import PreCorrectorGUI
from .MultiScan import ScanWidget
from .MultiSwitch import MultiSwitchGUI
from .Memory import ControllerMemory